pipeline:
  name: chatelo-quality-pipeline
  identifier: chatelo_quality_pipeline
  projectIdentifier: chatelo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: andrewgithubconnector
        repoName: chatelo-2
        build: <+input>
  stages:
    - stage:
        name: Testing
        identifier: Testing
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: newharnesscluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Oxlint and Oxfmt
                  identifier: Testing
                  spec:
                    connectorRef: harness_docker_reg
                    image: node:26-bookworm-slim
                    shell: Bash
                    command: |-
                      #!/usr/bin/env bash

                      set -euo pipefail

                      echo "Checking npm version"

                      npm --version

                      echo 'Installing Dependencies'
                      npm ci
                      echo 'DEPENDENCIES INSTALLED SUCCESSFULLY'

                      npm install oxfmt
                      npm install oxlint

                      echo 'Installed Oxlint and Oxfmt'
                      echo '#######################################################'
                      echo 'Running oxlint'

                      if npm run lint:ox; then
                          echo 'Oxlint Check Has Passed'
                      else
                          echo 'Oxlint Failed!'
                          exit 1
                      fi

                      if npm run format:check; then
                          echo 'Oxfmt Check Has Passed'
                      else
                          echo 'Oxfmt Failed!'
                          exit 1
                      fi
                      echo 'All Tests Passed Moving to Build Stage'
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "1"
    - stage:
        name: Build and Push
        identifier: Build_and_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: newharnesscluster
              namespace: harness-delegate-ng
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: Build and Push to GAR
                  identifier: Build_and_Push_to_GAR
                  spec:
                    connectorRef: <+input>
                    host: <+input>
                    projectID: <+input>
                    imageName: <+input>
                    tags:
                      - <+codebase.shortCommitSha>
                      - latest
                    dockerfile: Dockerfile
                    caching: true
                    resources:
                      limits:
                        memory: 4Gi
                        cpu: "2"
