pipeline:
  name: chatelo-quality-pipeline
  identifier: chatelo_quality_pipeline
  projectIdentifier: chatelo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: andrewgithubconnector
        repoName: chatelo-2
        build: <+input>
  stages:
    - stage:
        name: Testing
        identifier: Testing
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.harnesscluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Oxlint and Oxfmt
                  identifier: Testing
                  spec:
                    connectorRef: harness_docker_reg
                    image: node:26-bookworm-slim
                    shell: Bash
                    command: |-
                      #!/usr/bin/env bash

                      set -euo pipefail

                      echo "Checking npm version"

                      npm --version

                      echo 'Installing Dependencies'
                      npm ci
                      echo 'DEPENDENCIES INSTALLED SUCCESSFULLY'

                      npm install oxfmt
                      npm install oxlint

                      echo 'Installed Oxlint and Oxfmt'
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "1"
